### ISSUE TITLE
DGND3700 v.1 "Failed to query remote host."

### ISSUE THREAD

**Issue by ghost** [darkarnium/secpub#2]
Hello, I ran SOAPWNDR.rb against a Netgear DGND3700 v.1 N600 Wireless Dual Band Gigabit ADSL2+ Modem Router and the output was:

[!] Attempting to extract information from http://192.168.0.1:80/
[!] Failed to query remote host.

**Comment by darkarnium** [comment]
It looks like this model isn't affected. However, to confirm I will pull down the GPL package for this device later on this evening and have a quick look.

Cheers,
Peter

**Comment by ghost** [comment]
Ok thanks!  FYI I'm using <a href="http://www.richud.com/wiki/DGND3700_V1_Transmission_Firmware">this firmware</a> on it which is far better than the stock.

**Comment by darkarnium** [comment]
Not a problem. A third-party firmware build should not be affected unless they are re-using the NetGear 'net-cgi' binary, which in this case is doubtful as it looks like the underlaying Linux platform is different to the devices affected by this vulnerability.

In order to confirm this I have had a cursory glance over the 'DGND3700_V1.0.0.12NA_src_full.zip' GPL package from NetGear this evening and it looks like you should be safe from this particular vulnerability.

Cheers,
Peter
